import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ConvexClientProvider from "@/components/Provider/ConvexClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yuvidew108",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ConvexClientProvider>
        <Toaster position="bottom-center" />
        {children}
      </ConvexClientProvider>
      </body>
    </html>
  );
}
